kind: pipeline
name: default

steps:
- name: test
  image: golang
  environment:
    CGO_ENABLED: 0
    ARN_ROOT: /drone/src
  commands:
  - apt-get -y install nodejs
  - go version
  - npm install -g typescript
  - go mod download
  - make tools
  - make assets
  - make server
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
  - golangci-lint run
  - make db
  - go test -v -coverprofile=coverage.txt .

- name: coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov-token
    files:
      - coverage.txt

- name: discord
  image: appleboy/drone-discord
  when:
    status:
    - failure
  settings:
    webhook_id:
      from_secret: discord-id
    webhook_token:
      from_secret: discord-token
