run:
  skip-dirs:
    components

linters:
  enable-all: true
  disable:
    - dupl
    - lll
    - goconst
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - maligned
    - stylecheck
    - funlen