version: "3.7"
services:
  notify.moe:
    build:
      context: .
      dockerfile: docker/development.Dockerfile
    image: animenotifier/notify.moe
    hostname: docker
    container_name: notify.moe
    stdin_open: true
    tty: true
    ports:
      - "443:4001"
    volumes:
      - ~/:/my

networks:
  default:
    name: notify.moe