version: "3.7"
services:
  notify.moe:
    build:
      context: .
      dockerfile: docker/development.Dockerfile
      network: host
    image: animenotifier/notify.moe
    hostname: arn
    container_name: notify.moe
    stdin_open: true
    tty: true
    network_mode: host
    ports:
      - "443:4001"
    volumes:
      - ~/:/my