version: "3.4"
services:
  notify.moe:
    build:
      context: .
      dockerfile: docker/development.Dockerfile
      network: host
    image: animenotifier/notify.moe
    hostname: docker
    stdin_open: true
    tty: true
    network_mode: host
    ports:
      - "443:4001"
    volumes:
      - ~:/my